project:
  type: website
  output-dir: docs

website:
  title: "Bush Heritage R Workshops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: day1.qmd
        text: July 23rd - Intro to R
      - href: day2.qmd
        text: July 24th - Intro to Modelling
      - href: day3.qmd
        text: July 25th - Advanced Modelling
      - href: about.qmd
        text: Meet your instructors
        
resources: 
    - "data/*"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

