---
title: "Advanced Modelling in R"
format: html
theme: sandstone
author-title: Made for
author: Bush Heritage
toc: true
toc-location: left
toc-title: Content
toc-depth: 4
published-title: Date
date: 2024-02-13
editor: visual
embed-resources: true
---

# Statistical modelling in R for ecologists (Part 2)

Here we build upon modelling skills developed in [Part 1](insert link) of this coarse. In **Part 1** we learned how to fit models to data in a *frequentist* paradigm. 

Here we will fit the same models in a *bayesian* paradigm. Then we will build more complex, multivariate bayesian models, to demonstrate when they might be preferred over over frequentist approaches.

## General(ised) linear models in a Bayesian framework

-   Bayesian parameter estimation

-   max likelihood to MCMC sampling

-   Bayesian glm (univariate) - repeat same examples from yesterday

## Multivariate response

- nmds

- multivariate GLM - its the same thing

## Spatial multivariate GLM - a joing species distribution model

-   Why Bayesian? complex models (e.g., spatial random effects), low sample size and prior information

-   multivariate, spatial GLM (or wait till day 2 and make it a spatial example?)

- Make a spatial interactive map

